# Build matrix
language: node_js
matrix:
  include:

    # Run linter once
    - node_js: '4'
      env: LINT=true

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Build script
script:
  - 'if [ $LINT ]; then npm run lint; fi'